#
# Makefile for motor chip drivers.
#


obj-$(CONFIG_MOTOR_CLASS)			+= motor_sys.o
obj-$(CONFIG_MOTOR_28BYJ_48)		+= motor_28byj_48.o
obj-$(CONFIG_MOTOR_DC)				+= motor_dc.o
obj-$(CONFIG_MOTOR_L293D_DC)		+= motor_l293d_dc.o
obj-$(CONFIG_MOTOR_L293D_STEPPER)	+= motor_l293d_stepper.o